# Single Dimension NumPy Array

In [1]:
!pip install numpy

In [5]:
import numpy as np #np is an alias
arr= np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
type(arr)

numpy.ndarray

# MultiDimesional NumPy Array

In [2]:
import numpy as np
n2= np.array([[1,2,3],[4,5,6]])
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
n2=np.zeros((3,3))
n2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
n2 = np.eye(2, 3)
print(n2)

[[1. 0. 0.]
 [0. 1. 0.]]


# initialization of a array of matrix with full then

In [24]:
n4= np.full((3,3),8)
n4

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

# initialization of numpy array within a range

In [26]:
n5= np.arange(1,10)
n5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# initialization of numpy arrange with the skip number

In [27]:
n5= np.arange(1,10,3)
n5

array([1, 4, 7])

# initialization of numpy array with random numbers

In [30]:
otp= np.random.randint(100,1000,10)
otp

array([308, 583, 756, 692, 282, 323, 573, 228, 866, 621])

# initialization of array shape which changes in a fraction of second

In [33]:
n1= np.array([[1,2,3],[2,1,3],[2,1,2],[1,2,3]])

In [34]:
n1.shape

(4, 3)

In [38]:
n1.shape=(3,4)
n1

array([[1, 2, 3, 2],
       [1, 3, 2, 1],
       [2, 1, 2, 3]])

# joining the numpy array

In [46]:
a= np.array([1,2,3,4,5,6,7,8,9,10])
b= np.array([10,20,30,40,50,60,70,80,90,100])
c= np.array([11,22,33,44,55,66,77,88,99,00])
d= np.array([29,39,49,59,69,79,89,19,32,15])

In [47]:
np.vstack((a,b,c,d))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99,   0],
       [ 29,  39,  49,  59,  69,  79,  89,  19,  32,  15]])

In [48]:
np.hstack((a,b,c,d))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  10,  20,  30,
        40,  50,  60,  70,  80,  90, 100,  11,  22,  33,  44,  55,  66,
        77,  88,  99,   0,  29,  39,  49,  59,  69,  79,  89,  19,  32,
        15])

In [50]:
np.column_stack((a,b,c,d))

array([[  1,  10,  11,  29],
       [  2,  20,  22,  39],
       [  3,  30,  33,  49],
       [  4,  40,  44,  59],
       [  5,  50,  55,  69],
       [  6,  60,  66,  79],
       [  7,  70,  77,  89],
       [  8,  80,  88,  19],
       [  9,  90,  99,  32],
       [ 10, 100,   0,  15]])

# numpy intersection and differences

In [54]:
a= np.array([1,2,3,4,5,6,7,8,9,10])
d= np.array([2,1,88,22,99,10])

In [55]:
np.intersect1d(a,d)

array([ 1,  2, 10])

In [56]:
np.setdiff1d(a,d)

array([3, 4, 5, 6, 7, 8, 9])

# addition of numpy arrays

In [57]:
a= np.array([1,2,3,4])
d= np.array([2,1,88,22])

In [58]:
np.add(a,d)

array([ 3,  3, 91, 26])

In [60]:
np.sum([a,d])

123

In [61]:
np.sum([a,d],axis=1)

array([ 10, 113])

In [62]:
np.sum([a,d],axis=0)

array([ 3,  3, 91, 26])

In [64]:
np.sum([a,d],axis=0)

array([ 3,  3, 91, 26])

# numpy array mathematics

In [65]:
p=np.array([10,20,30])

In [66]:
p+1

array([11, 21, 31])

In [68]:
p%3

array([1, 2, 0], dtype=int32)

In [69]:
p/3

array([ 3.33333333,  6.66666667, 10.        ])

In [70]:
p-2

array([ 8, 18, 28])

# numpy math functions

In [76]:
n= np.array([10,20,30,99,22])

In [77]:
np.mean(n)

36.2

In [78]:
np.median(n)

22.0

In [80]:
np.var(n)

1026.56

In [82]:
np.std(n)

32.03997503120126

In [84]:
np.cov(n)

array(1283.2)

# saving and loading numpy array

In [88]:
arr = np.array([1, 2, 3, 4, 5])
np.save('binisha.npy', arr)

In [89]:
np.load('binisha.npy')

array([1, 2, 3, 4, 5])

# Einstein Summation Convention


# Einsum
This function is used to compute many multi dimensional and linear algebraic operations on arrays

In [5]:
import numpy as np
a= np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [17]:
a= np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
b= np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
c=np.arange(31,40).reshape(3,3)
np.einsum('ii->i',a)
np.einsum('ii->i',b)
np.einsum('ii->i',c)

array([31, 35, 39])

In [14]:
np.einsum('ij->ji',c)

array([[31, 34, 37],
       [32, 35, 38],
       [33, 36, 39]])

In [18]:
np.einsum('ii',a)

15

In [22]:
a=np.array([[10,20],[20,30],[40,50]])
x=np.array([5,6])
print(np.einsum('ij,j->i',a,x))

[170 280 500]


In [25]:
arr=np.linspace(10,100,500).reshape(25,20)
np.savetxt('array.txt',arr)

In [26]:
np.loadtxt('array.txt')

array([[ 10.        ,  10.18036072,  10.36072144,  10.54108216,
         10.72144289,  10.90180361,  11.08216433,  11.26252505,
         11.44288577,  11.62324649,  11.80360721,  11.98396794,
         12.16432866,  12.34468938,  12.5250501 ,  12.70541082,
         12.88577154,  13.06613226,  13.24649299,  13.42685371],
       [ 13.60721443,  13.78757515,  13.96793587,  14.14829659,
         14.32865731,  14.50901804,  14.68937876,  14.86973948,
         15.0501002 ,  15.23046092,  15.41082164,  15.59118236,
         15.77154309,  15.95190381,  16.13226453,  16.31262525,
         16.49298597,  16.67334669,  16.85370741,  17.03406814],
       [ 17.21442886,  17.39478958,  17.5751503 ,  17.75551102,
         17.93587174,  18.11623246,  18.29659319,  18.47695391,
         18.65731463,  18.83767535,  19.01803607,  19.19839679,
         19.37875752,  19.55911824,  19.73947896,  19.91983968,
         20.1002004 ,  20.28056112,  20.46092184,  20.64128257],
       [ 20.82164329,  21.00200401,  

In [28]:
a= np.array([1,2,3])
b=np.array([5,6,7])
np.concatenate([a,b])

array([1, 2, 3, 5, 6, 7])

In [33]:
c=np.array([1,2,3,4,5,6,7,8,9])
c1,c2,c3=np.split(c,[3,5])
print(c1,c2,c3)

[1 2 3] [4 5] [6 7 8 9]


In [36]:
grid= np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
a=np.array([10,30,40,90])
np.mean((90-42.5)/np.std(a))

1.6115589663919447

In [47]:
m=([-1.10,-0.42,-0.08,1.61])
np.mean(m)

0.0025000000000000022

In [58]:
arr= np.array([10,30,40,50])
mean=np.mean(arr)
std=np.std(arr)
for item in arr:
    print((item-mean)/std)



-1.52127765851133
-0.16903085094570333
0.50709255283711
1.1832159566199232


In [15]:
arr= np.array([10,30,40,50])
mean=np.mean(arr)
std=np.std(arr)
q=[]
for item in arr:
    r=(item-mean)/std
    print(r)
    q.append(r)
print(f'{q)
np.mean(q)

-1.52127765851133
-0.16903085094570333
0.50709255283711
1.1832159566199232
[-1.52127765851133, -0.16903085094570333, 0.50709255283711, 1.1832159566199232]


0.0